### ISSUE TITLE
style contract broken

### ISSUE THREAD

**Issue by ABuarque** [ABuarque/huffman#2]
@arqui456, at the files on priority queue curly braces have not been put at same line of label function, as it's shown below:
`PriorityQueue *createPriorityQueue()
{
	PriorityQueue *newQueue = malloc(sizeof(PriorityQueue));
	if(!newQueue) return NULL;
	newQueue->head = NULL;
	newQueue->size = 0;

	return newQueue;
}`

**Comment by arqui456** [comment]
gonna fix it now

**Comment by arqui456** [comment]
fixed
